image: python:buster

stages:
  - test

coverage:
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install pdm
    - pdm install
  script:
    - pdm run pytest --cov=main tests/

pre-commit:
  stage: test
  before_script:
    - pip install --upgrade pip
    - pip install --upgrade pre-commit 
  script: 
    - pre-commit run --all-files